### PR TITLE
useApiMutation hook

### LINKED ISSUE #28: Mutations
## Summary

Mutations are a common feature in data-fetching libraries:
* https://github.com/tannerlinsley/react-query#mutations
* https://www.apollographql.com/docs/react/data/mutations/

While I don't find this is _fully_ necessary in many cases, since you can call `api.request()` directly, there is lots of value in building a transaction / rollback strategy, for example:

1. Managing a loading state to return from the hook and use in the UI
1. Optimistically updating the cache value
1. Making multiple API calls which are all required for a successful completion

* If _one_ API call fails, we want to roll back to the original value
* In-between the API requests, we don't want the cache to be optimistically updated multiple times. While this could be jarring for the user, it may also introduce bugs. For example, if you're incrementing a counter really quickly with a button, we could optimistically show the last-pressed button, but the API will keep resetting it after each successive API call completes.

An explicit mutations API which supports an optimistic response could solve the above issues.

Additionally, the optimistic setter should accept a "setter" function in addition to just passing the new response directly. This would help to facilitate updating the response relative to the previous response in a deterministic way, similar to `react#useState`'s function setter options.

------

## Goals

* Allow a minimal mutation to be performed without much boilerplate
* Allow various API methods to be accessed, such as `request`, `writeCachedResponse`, `readCachedResponse`, `buildUrl`, etc. that may be useful during the mutation. Event handlers such as `onError` and `onCachedUpdate` should _not_ be accessible during the mutation.
* Should manage a `loading` flag to be returned in the hook while the mutation is occurring
* There should be an optimistic mutation option which allows for setting the cache values in a transaction, so the cached response can be updated for the mutation query or any other query and can be rolled back if the `request`(s) fails
* Concurrent requests should be allowed, with the most recent optimistic response being respected. Also, the `loading` flag should remain `true` while _any_ requests are going on.
* Default fetch policy of the mutation `request` method should only be `no-cache`, and should be customizable via `ApiProvider`.

## Usage Examples

Optimistic update pattern with key-value cache:

```tsx
import {useApiMutation, useApiQuery} from 'fairlight'

const {showSnackbar} = useSnackbar()
const {handleUnexpectedError} = useErrorHandler()
const [users, usersQueryActions] = useApiQuery(UserEndpoints.list())
const [user, userQueryActions] = useApiQuery(UserEndpoints.findById(props.id))
const [updateUser, {loading: updatingUser}] = useApiMutation({
  mutation: (values, formikBag) => async ({request, setOptimisticResponse}) => {
    // transform data into request body payload
    const updatePayload = transformDataForUpdate(values)

    // optimistically update the UI
    const commitUser = setOptimisticResponse(
      UserEndpoints.findById(1),
      (prev) => ({...prev, ...updatePayload})
    )
    const commitUsers = setOptimisticResponse(UserEndpoints.list(), (prev) =>
      prev.map((prevUser) => {
        return prevUser.id === prop.id ? {...prevUser, updatePayload} : prevUser
      })
    )

    // make request(s)
    // - `deduplicate` is always `false`
    // - `fetchPolicy` is always `fetch-first` or `no-cache`
    const updatedUser = await request(
      UserEndpoints.partialUpdate(props.id, updatedUser)
    )

    // now we need to replace the cached versions with
    // the correct versions
    commitUser(updatedUser)
    commitUsers((prev) =>
      prev.map((prevUser) => {
        return prevUser.id === prop.id ? updatedUser : prevUser
      })
    )

    // we may even want to refetch these related queries instead
    usersQueryActions.refetch()
    userQueryActions.refetch()

    showSnackbar({
      variant: 'Success',
      message: `User '${updatedUser.name}' has been updated.`
    })
  },

  onError(error, {args}) {
    handleFormError(error, args[1], 'An error occurred')
  }
})
```

Potential future-version if we start supporting a normalized cache:

```tsx
import {useApiMutation, useApiQuery} from 'fairlight'

const {showSnackbar} = useSnackbar()
const {handleUnexpectedError} = useErrorHandler()
const [users, usersQueryActions] = useApiQuery(UserEndpoints.list())
const [user, userQueryActions] = useApiQuery(UserEndpoints.findById(props.id))
const [updateUser, {loading: updatingUser}] = useApiMutation({
  mutation: (values, formikBag) => async ({request}) => {
    // transform data into request body payload
    const updatePayload = transformDataForUpdate(values)

    const updatedUser = await request(
      UserEndpoints.partialUpdate(props.id, updatePayload),
      {
        // must be set directly on the `request` because
        // it doesn't have a way to match up request body
        // to identify the correct request (ie. running multiple `POST` requests)
        optimisticResponse: {
          ...user.data,
          ...updatePayload
        }
      }
    )

    // we may even want to refetch these related queries
    userQueryActions.refetch()

    showSnackbar({
      variant: 'Success',
      message: `User '${updatedUser.name}' has been updated.`
    })
  },

  onError(error, {args}) {
    handleFormError(error, args[1], 'An error occurred')
  }
})
```

### LINKED ISSUE #37: Default `api.request#defaultFetchPolicy` to `no-cache`
We should remove the ability to set the default fetch policy in the Api client constructor directly. Also, it should default to `no-cache`.

**Rationale:**

Originally, the default `api.request` policy was set to `fetch-first` so that the cache is used by default for responses when making mutations. However, that's only usually the case if you're using a normalized cache.. otherwise, a `PATCH /:id` response would not automatically update the `GET /:id`'s API response (which is the primary benefit of caching mutation responses).

With this in mind, and especially since the Mutations API (#28) will be able to provide its own default fetch policy anyway, I'm not confident that we should default `api.request` responses to `fetch-first`.

### PR DESCRIPTION
**Pull request by thomasdashney**
**Added `useApiMutation` hook (resolves #28):**
```tsx
const [createUser, {mutating: creatingUser}] = useApiMutation({
  mutation: (firstName: string, lastName: string) => async (api) => {
    return api.request(UserEndpoints.create({firstName, lastName}))
  },
  onError: (error) => console.error(error),
  onSuccess: (user) => console.log(`Created user ${firstName}`)
})

// usage
createUser('Thomas', 'Dashney')
```

Notes about API decisions:
* Mutation arguments can be whatever you want. The `mutation` property is curried so it can pass `api` helpers (a subset of `api` class methods), primarily so that the types can be inferred for the mutation function (`createUser` in the example)
* `onError` reduces the need to add a `try/catch` block
* `onSuccess` allows for logic to run once the mutation completes. It's worth noting that if an error occurs _inside_ the `onSuccess` handler, `onError` will not trigger. This is important because the error handler should only apply to the actual mutation operation.
* `request`'s default fetch policy is `no-cache` by default, but can be overridden via `ApiProvider` or per-request.

**Removed `Api#defaultFetchPolicy` (resolves #37)**
* Now that we have mutations, I can't think of a good reason to keep `defaultFetchPolicy`, since this was just added for mutations. Also, this now defaults to `no-cache` (which I think is the most sensible default for making the rare raw api call).

### CODE REVIEW

File: src/react/use-api-mutation/index.tsx [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+    } catch (error) {
+      if (params.onError) {
+        return params.onError(error, {mutationArgs})
+      }
+      throw error
+    } finally {
+      deregisterMutation()
+    }
+
+    params.onSuccess?.(returnValue, {mutationArgs})
```
Comment (azmenak) [inline src/react/use-api-mutation/index.tsx:48]: Is there a reason this needs to run after the try-catch block?

Comment (thomasdashney) [reply src/react/use-api-mutation/index.tsx:48]: This way, if an error occurs inside the `onSuccess` handler, `onError` will not trigger. This could avoid situations where a success snackbar shows via `onSuccess`, but then an error occurs after that, causing `onError` to be called and immediately triggering an error snackbar. I figure it's more clear that `onError` is only called if the actual `mutation` fails

TBH I was originally not going to add the `onSuccess` callback at all, but I think the above distinction justifies it's usefulness. It's also consistent with other popular data-fetching libraries. LMK what you think

Comment (azmenak) [reply src/react/use-api-mutation/index.tsx:48]: Makes sense!
